import type { Metadata } from "next";
import { Poppins } from "next/font/google"
import "./globals.css";

const font = Poppins({
  subsets: ["latin"],
  weight: ["300", "700"],
  variable: "--font-poppins"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} m-3`}
      >
        {children}
      </body>
    </html>
  );
}
